### ISSUE TITLE
Compilation error w/ OpenCV2 file

### ISSUE THREAD

**Issue by mankoff** [Nerei/kinfu_remake#8]
```
/usr/include/opencv2/contrib/contrib.hpp:273:23: error: ‘vector’ does not name a type
         Octree( const vector<Point3f>& points, int maxLevels = 10, int minPoints = 20 );
```

I'm just doing `cmake ..` and then `make` from a `build` sub-folder, but the make crashes fairly quickly with the above error. I have all dependencies installed including opencv2 and opencv3.

**Comment by Nerei** [comment]
Hm.. It seems OpenCV bug. Anyway removed `opencv2/contrib/contrib.hpp` include

**Comment by Nerei** [comment]
Hm.. It seems OpenCV bug. Anyway I removed `#include opencv2/contrib/contrib.hpp` and this should fix it.

**Comment by mankoff** [comment]
Fixed. Thanks!
