### ISSUE TITLE
Unknown SM version 5.0! Problem

### ISSUE THREAD

**Issue by sotoglzz** [Nerei/kinfu_remake#9]
Hi, thanks for the source code.
I've compiled without errors but I have a little problem when I'm trying to run demo executable:

~ $ sudo /home/trinidad/kinfu_remake/build/bin/demo
Device 0:  "GeForce GTX 750 Ti"  2047Mb
Can't determine number of cores. Unknown SM version 5.0!
, sm_50, 0 cores, Driver/Runtime ver.7.50/7.50
KinFu2 error: invalid device function	/home/trinidad/kinfu_remake/kfusion/src/cuda/tsdf_volume.cu:38

My kinect 1414 works perfectly fine. I installed Cuda-7.5, Openni from git repository, opencv-2.4.8 (only core, highgui, imgproc and viz modules with shared _libs)
I really don't know what is the problem, if someone can help me a little that would be great!!.
I'm using linux mint mate 17.2 Rafaela mate edition 64 bits

Bye, in advance
José Soto

**Comment by Nerei** [comment]
Just add compilation flag here for Maxwell GPU here:
https://github.com/Nerei/kinfu_remake/blob/master/CMakeLists.txt#L32

Append after semicolon `-gencode;arch=compute_50,code=sm_50`

PR is appreciated

**Comment by sotoglzz** [comment]
Thank you so much.
That was the solution, It works amazing.
Thanks again for the source code

Jose Soto

**Comment by Nerei** [comment]
Fixed in https://github.com/Nerei/kinfu_remake/pull/11

**Comment by ieted** [comment]
I met exactly the same problem using NVIDIA Tesla K80. It tells me as follows:
```
Device 0:  "Tesla K80"  11520Mb
Can't determine number of cores. Unknown SM version 3.7!
, sm_37, 0 cores, Driver/Runtime ver.7.50/7.50
KinFu2 error: Init failed: Can't create any node of the requested type!
```
I tried to add compilation flag in CMakeLists.txt as `-gencode;arch=compute_30,code=sm_37`, but still got the error. 
Anyone can give me any advice? Thanks in advance.
